title = "Kendrick Lamar"
old_id = 81
year = 0
location = "Under Sol"
description = """
"""
tags = [ "needs_more_information" ]
artists = []

[[images]]
filename = "kendrick.jpg"
date = 2023-11-05
by = "Erin Monahan"
alt = "TODO"
